version: '3.8'

services:
  # Serviço para a aplicação
  ecommerce-backend:
    build: .
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do container para a 8080 do host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql  # Garante que o MySQL seja iniciado primeiro

  # Serviço para o banco de dados (MySQL)
  mysql:
    image: mysql:8.0  # Usa a imagem oficial do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Senha do usuário root do MySQL
      MYSQL_DATABASE: ecommerce  # Nome do banco de dados a ser criado
    ports:
      - "3306:3306"  # Mapeia a porta 3306 do MySQL para a porta 3306 do host
    volumes:
      - mysql-data:/var/lib/mysql  # Persiste os dados do banco de dados

# Volumes para persistência de dados
volumes:
  mysql-data:
    driver: local